apiVersion: apps/v1
kind: Deployment
metadata:
  name: {servicio}-deployment
spec:
  selector:
    matchLabels:
      app: servicio-server
  replicas: 1
  template:
    metadata:
      labels:
        app: servicio-server
    spec:
      containers:
      - name: servicio-container
        image: docker.io/{docker_user}/{servicio}:{github.sha}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: servicio-service
  name: servicio-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: servicio-server
  type: LoadBalancer
